openapi: 3.0.1
info:
  title: Onboarding API
  description: Plugin for managing a company's software onboarding process, you can view and filter software, clients, and permissions.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /software:
    get:
      operationId: getSoftware
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Software'
      summary: Get all software
  /software/{id}:
    get:
      operationId: getSoftwareById
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Software'
      summary: Get a specific software by ID
  /software/{id}/clients:
    get:
      operationId: getClientsBySoftwareId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
      summary: Get all clients for a specific software
  /software/{id}/permissions:
    get:
      operationId: getPermissionsBySoftwareId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Permission'
      summary: Get all permissions for a specific software
  /client:
    get:
      operationId: getClients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
      summary: Get all clients
  /client/{id}:
    get:
      operationId: getClientById
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
      summary: Get a specific client by ID
  /client/{id}/software:
    get:
      operationId: getSoftwareByClientId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Software'
      summary: Get all software for a specific client
  /permission:
    get:
      operationId: getPermissions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Permission'
      summary: Get all permissions
  /permission/{id}:
    get:
      operationId: getPermissionById
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'
      summary: Get a specific permission by ID
components:
  schemas:
    Software:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        internalCode:
          type: string
        tags:
          type: array
          items:
            type: string
        productOwner:
          type: string
        technicalOwners:
          type: array
          items:
            type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
    Client:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        software:
          type: array
          items:
            $ref: '#/components/schemas/Software'
    Permission:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        expiration:
          type: string
        technicalOwner:
          type: string
